### PR TITLE
Add VS Code Vim plugin bindings

### PR DESCRIPTION
**Pull request by WorldMaker**
I'm learning this Vim layout by trying to bind it in VS Code's Vim plugin

### CODE REVIEW

**Review by insidewhy — APPROVED** [review]
Thanks!

**Comment by insidewhy** [comment]
@WorldMaker Just started messing with vscode myself (is great for refactoring typescript), this was a big hand 👍

**Comment by insidewhy** [comment]
"u" for undo doesn't seem to work, seems it's a bug with vscodevim.

**Comment by insidewhy** [comment]
Opened this for the vscodevim issue: https://github.com/VSCodeVim/Vim/issues/2116

**Comment by WorldMaker** [comment]
Ah, I had wondered about that but hadn't followed through to see where the bug was. 👍

**Comment by insidewhy** [comment]
I fixed the bug in vscodevim, hopefully they'll merge my PR.

**Pull request merged**
